# Generated by Django 5.1.6 on 2025-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ca', models.CharField(max_length=50)),
                ('description_ca', models.TextField(blank=True, null=True)),
                ('price_ca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_ca', models.ImageField(blank=True, null=True, upload_to='categorys/')),
                ('email_ca', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/')),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
