# Generated by Django 5.1.6 on 2025-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='image',
        ),
        migrations.AddField(
            model_name='goods',
            name='email_ca',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
