# Generated by Django 5.1.6 on 2025-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0002_remove_goods_image_goods_email_ca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='email_ca',
        ),
        migrations.AddField(
            model_name='goods',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
