# Generated by Django 5.1.6 on 2025-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0003_remove_goods_email_ca_goods_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_ca',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
