# Generated by Django 5.1.6 on 2025-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0004_remove_category_image_ca_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
    ]
