# Generated by Django 5.1.6 on 2025-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0005_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.TextField(default=1, max_length=100, verbose_name='Категорії'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='email_ca',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ca',
            field=models.CharField(max_length=50, verbose_name='Товари'),
        ),
        migrations.AlterField(
            model_name='category',
            name='price_ca',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Товари'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
    ]
