# Generated by Django 5.1.6 on 2025-04-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0006_goods_category_alter_category_description_ca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
    ]
