# Generated by Django 5.1.6 on 2025-04-05 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0007_remove_goods_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Активна чи не активна'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_fish.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='goods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
    ]
