# Generated by Django 5.1.6 on 2025-04-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0008_remove_goods_title_category_order_goods_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='email',
        ),
    ]
