# Generated by Django 5.1.6 on 2025-04-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0009_remove_category_order_remove_goods_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='created_at',
        ),
    ]
