# Generated by Django 5.1.6 on 2025-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0012_remove_goods_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('name', models.CharField(max_length=100, verbose_name="Ваше ім'я")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('address', models.TextField(verbose_name='Адреса доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='email_ca',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='image',
        ),
        migrations.AddField(
            model_name='goods',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/', verbose_name='Зображення'),
        ),
    ]
