# Generated by Django 5.1.6 on 2025-05-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_fish', '0013_order_remove_category_email_ca_remove_goods_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='image_url',
            new_name='image',
        ),
    ]
